### ISSUE TITLE
the values of train loss are becoming negative

### ISSUE THREAD

**Issue by QingL0218** [marco-rudolph/differnet#10]
Hi, dear Marco. I have a quesion: when I use this code to train , the train losses from positive to negative ,  is it right ? I'm confused. Waiting for your reply.

Best Regards!

**Comment by marco-rudolph** [comment]
This is absolutely normal. The loss indicates the negative log likelihood, which can be quite negative.

**Comment by QingL0218** [comment]
ok, thank you very much !
