### ISSUE TITLE
Histogram - Figure 6

### ISSUE THREAD

**Issue by bnascimento** [marco-rudolph/differnet#13]
Hi @marco-rudolph , thank you for sharing your work.
I have a couple questions while trying to replicate your work on the MVTec-AD dataset.
On the paper is claimed to train during 192 epochs. Is that 24 epochs x 8 subepochs?
Also do you have a code snippet to generate the Figure 6 histogram?

Best regards,
Bruno

**Comment by marco-rudolph** [comment]
Hi!
> Is that 24 epochs x 8 subepochs?
Exactly.
> Also do you have a code snippet to generate the Figure 6 histogram?
Yes, no problem:
`import matplotlib.pyplot as plt

def compare_histogram(scores, classes, save_filepath, thresh=3, n_bins=64):
    '''
    scores: array of anomaly scores with shape (N,) with N as number of samples
    classes: array of classes with 0 as non-defect and 1 as defect with shape (N,)
    thresh: maximum score in histogram
    n_bins: number of bins to show in histogram
    '''
    scores[scores > thresh] = thresh
    
    bins = np.linspace(np.min(scores), np.max(scores), n_bins)

    scores_norm = scores[classes == 0]
    scores_ano = scores[classes == 1]
    
    plt.clf()
    plt.hist(scores_norm, bins, alpha=0.5, density=True, label='non-defects', color='cyan', edgecolor = "black")
    plt.hist(scores_ano, bins, alpha=0.5, density=True, label='defects', color='crimson', edgecolor = "black")

    ticks = np.linspace(np.min(scores), thresh, 5)
    labels = [str(i) for i in ticks[:-1]] + ['>' + str(thresh)]
    plt.xticks(ticks, labels=labels)
    plt.xlabel('Anomaly Score')
    plt.ylabel('Count (normalized)')
    plt.legend()
    plt.grid(axis='y')
    plt.savefig(save_filepath, bbox_inches = 'tight', pad_inches = 0)`

**Comment by marco-rudolph** [comment]
Hi!
> Is that 24 epochs x 8 subepochs?

Exactly.
> Also do you have a code snippet to generate the Figure 6 histogram?

Yes, no problem:

```
import matplotlib.pyplot as plt
import numpy as np

def compare_histogram(scores, classes, save_filepath, thresh=3, n_bins=64):
    scores[scores > thresh] = thresh
    
    bins = np.linspace(np.min(scores), np.max(scores), n_bins)

    scores_norm = scores[classes == 0]
    scores_ano = scores[classes == 1]
    
    plt.clf()
    plt.hist(scores_norm, bins, alpha=0.5, density=True, label='non-defects', color='cyan', edgecolor = "black")
    plt.hist(scores_ano, bins, alpha=0.5, density=True, label='defects', color='crimson', edgecolor = "black")

    ticks = np.linspace(np.min(scores), thresh, 5)
    labels = [str(i) for i in ticks[:-1]] + ['>' + str(thresh)]
    plt.xticks(ticks, labels=labels)
    plt.xlabel('Anomaly Score')
    plt.ylabel('Count (normalized)')
    plt.legend()
    plt.grid(axis='y')
    plt.savefig(save_filepath, bbox_inches = 'tight', pad_inches = 0)
```

**Comment by bnascimento** [comment]
Thank you
