### ISSUE TITLE
Test code 

### ISSUE THREAD

**Issue by nxm19830306** [marco-rudolph/differnet#15]
Hi, 

     Can you submit the test code to predict the image result according to the trained model? 
     Thanks!

**Comment by jeff-ai-deep-learning** [comment]
Get following issue, when I run the program
\functional.py:942: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(

**Comment by marco-rudolph** [comment]
Use [this script](https://github.com/marco-rudolph/differnet/blob/b4d7301c8601048fea955ad6860dcb072a639af8/evaluate.py) to get scores from images of one directory.

**Comment by marco-rudolph** [comment]
> Get following issue, when I run the program
> \functional.py:942: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
> warnings.warn(

Wow, this is so misplaced here and does not seem to be a problem that is directly related to this repo.
