### ISSUE TITLE
How is θ given

### ISSUE THREAD

**Issue by renqiqi** [marco-rudolph/differnet#19]
Hi，
How is θ given? Is it artificially set or calculated? If it is calculated, how is it calculated?
Looking forward to your reply.

**Comment by marco-rudolph** [comment]
There is no fix theta. Firstly, it depends on the dataset. Secondly it depends on the desired false positive rate. You could use a validation set (by splitting the test set) to get a feeling for the distribution of anomaly scores of normal data.

**Comment by renqiqi** [comment]
> There is no fix theta. Firstly, it depends on the dataset. Secondly it depends on the desired false positive rate. You could use a validation set (by splitting the test set) to get a feeling for the distribution of anomaly scores of normal data.

I got it, thanks for your reply.
