### ISSUE TITLE
Magnatice tile dataset train and test part

### ISSUE THREAD

**Issue by AmmarKamoona** [marco-rudolph/differnet#23]
Hi there, 
Can you share the train and test split for the magnetic tile dataset? 
The dataset from [13] does not provide this.
Evaluation on different split generates different results.

**Comment by marco-rudolph** [comment]
Hi,
[these samples](https://github.com/marco-rudolph/differnet/blob/13529c8a79508a930df3618cf6718358a87b8719/mtd_train_filenames.txt) were used for training. The rest was used for testing.

Best regards,
Marco Rudolph

**Comment by AmmarKamoona** [comment]
Thanks alot.
