### ISSUE TITLE
Get a gradient map from scored image

### ISSUE THREAD

**Issue by aditya-pratama96** [marco-rudolph/differnet#24]
I use the evaluate.py script to scores some images. 
How can I get the gradient map from the scored images?

**Comment by marco-rudolph** [comment]
[See here](https://github.com/marco-rudolph/differnet/blob/13529c8a79508a930df3618cf6718358a87b8719/train.py#L94) to see how to call the function to get gradient maps. [See here](https://github.com/marco-rudolph/differnet/blob/13529c8a79508a930df3618cf6718358a87b8719/main.py#L11) to see how to get the test dataloader for that.
Alternatively you could use and modify the code of [this file](https://github.com/marco-rudolph/differnet/blob/13529c8a79508a930df3618cf6718358a87b8719/localization.py) directly. Watch out that gradient maps are only produced if the label is 1 (=anomaly).
