### ISSUE TITLE
when set grad_map_viz to be True, I got a mistake: rotate() got an unexpected keyword argument 'reshape'

### ISSUE THREAD

**Issue by imkelt** [marco-rudolph/differnet#27]
when set **grad_map_viz** to be True, I got a mistake: **rotate() got an unexpected keyword argument 'reshape'**.
could you please fix it!!! thanks a lot for you work!!!

**Comment by marco-rudolph** [comment]
Hi,
I could not reproduce the error. Did you accidently uncommentet [this line](https://github.com/marco-rudolph/differnet/blob/13529c8a79508a930df3618cf6718358a87b8719/localization.py#L5)? I guess your interpreter did not call scipy.ndimage.rotate, but another 'rotate'-function.

Thank you,
Marco

**Comment by imkelt** [comment]
thanks to you reply! the commit 13c79a4 works well，may the problem of environment？I haven't modified any code.

**Comment by marco-rudolph** [comment]
And the current commit does not work for you?

**Comment by imkelt** [comment]
yeah. The current commit would have the above problem.

**Comment by marco-rudolph** [comment]
Thanks for the comment, I have fixed the error.

**Comment by imkelt** [comment]
Thanks for your work!!!
