### ISSUE TITLE
How to train anomaly data set to improve accuracy ?

### ISSUE THREAD

**Issue by rfuk0503** [marco-rudolph/differnet#28]
Is there any way to train anomaly images such as to modify Loss Function get_loss() ?
Assuming that I got anomaly images after DifferNet trainning done.

**Comment by marco-rudolph** [comment]
This is not foreseen in this method. Theoretically, one could use the negative loss in this case to minimize the likelihood, but I guess in this case the model would become unstable and would need regularization for these cases.

**Comment by rfuk0503** [comment]
Thank you for your quick reply.
