### ISSUE TITLE
error when I run command 

### ISSUE THREAD

**Issue by valadad** [marco-rudolph/differnet#31]
Hi 

I face an error when I run `python main.py`

![image](https://user-images.githubusercontent.com/56509851/131537816-d42b0d52-1df4-42ad-9963-faef3307f0cc.png)

thanks

**Comment by marco-rudolph** [comment]
Hi,
hope this helps:
https://github.com/pytorch/pytorch/issues/33655
In the case you have no GPU: The code does not support torch with CPU, so you would have to refactor it.
