### ISSUE TITLE
AttributeError: 'ImageFolderMultiTransform' object has no attribute '_find_classes'

### ISSUE THREAD

**Issue by volkov-maxim** [marco-rudolph/differnet#32]
Hi!
When I ran main.py I got runtime error:

> py main.py
> Traceback (most recent call last):
>   File "C:\Projects\bricky\defect_detection\differnet\main.py", line 10, in <module>
>     train_set, test_set = load_datasets(c.dataset_path, c.class_name)
>   File "C:\Projects\bricky\defect_detection\differnet\utils.py", line 104, in load_datasets
>     trainset = ImageFolderMultiTransform(data_dir_train, transform=transform_train, n_transforms=c.n_transforms)
>   File "C:\Projects\bricky\defect_detection\differnet\multi_transform_loader.py", line 67, in __init__
>     super(ImageFolderMultiTransform, self).__init__(root, loader, IMG_EXTENSIONS,
>   File "C:\Projects\bricky\defect_detection\differnet\multi_transform_loader.py", line 34, in __init__
>     classes, class_to_idx = self._find_classes(self.root)
> AttributeError: 'ImageFolderMultiTransform' object has no attribute '_find_classes'

I think that this error causes due the typo in "differnet\multi_transform_loader.py" (line 34). `DatasetFolder` object haven't `_find_classes` method, instead of [it has `find_classes` method](https://pytorch.org/vision/stable/datasets.html?highlight=_classes#torchvision.datasets.DatasetFolder.find_classes).

**Comment by marco-rudolph** [comment]
#29 
> For the new torchvision version, use
> `classes, class_to_idx = self.find_classes(self.root) `

**Comment by marco-rudolph** [comment]
Thanks for the hint, I will do a commit where it works with both torchvision versions.

**Comment by volkov-maxim** [comment]
Sorry for duplicate 😏

**Comment by marco-rudolph** [comment]
no problem - you can say the subject of the old issue was not helpful at all...
