### ISSUE TITLE
How to improve accuracy of the localisation of anomalies at gradient map?

### ISSUE THREAD

**Issue by volkov-maxim** [marco-rudolph/differnet#34]
Hi, Marco!

When I visualise the gradient map, I get incorrect localisation of anomalies (see examples below).
For me, the ideal is when gradients repeat the contour of the anomaly. Is it possible?

? How can I improve the accuracy of the localisation of anomalies on gradient map?

![0_orig](https://user-images.githubusercontent.com/44219431/133975949-34993f32-f100-43fb-a71b-cc391dfd6715.png)
![0_gradient_map](https://user-images.githubusercontent.com/44219431/133975946-b2b80207-2c10-422a-afb3-683a814b1047.png)
![5_orig](https://user-images.githubusercontent.com/44219431/133975957-f98c59c9-2847-4706-9db5-15e2553cd481.png)
![5_gradient_map](https://user-images.githubusercontent.com/44219431/133975955-76dd7b6c-e16a-4559-b3df-8c9df7985903.png)
![19_orig](https://user-images.githubusercontent.com/44219431/133975967-fa2db32b-5d23-4929-9e69-3ee667e2012f.png)
![19_gradient_map](https://user-images.githubusercontent.com/44219431/133975965-d0ec5a39-48e0-441a-858a-e20d7058aea9.png)
![13_orig](https://user-images.githubusercontent.com/44219431/133976312-104bad4b-08dc-4177-8958-78759f4de825.png)
![13_gradient_map](https://user-images.githubusercontent.com/44219431/133976308-37f782a0-fdfc-467d-8b50-c02aa04926e5.png)

**Comment by marco-rudolph** [comment]
Unfortunately, there are some failure cases for the localization. I would recommend techniques that are specialized on localization like [this technique](https://github.com/xiahaifeng1995/PaDiM-Anomaly-Detection-Localization-master).
