### ISSUE TITLE
Qualitative results between CS-Flow and DifferNet on MTD dataset

### ISSUE THREAD

**Issue by sungwool** [marco-rudolph/differnet#37]
Hello, I'm interested in your method. 

While reading your papers(DifferNet, CS-Flow), I got a question. 

The *1-NN performance in the DifferNet paper is recorded as 80.0 but in the CS-Flow paper, it is recorded as 97.7. 
(*Method for "Are pretrained cnns good feature extractors for anomaly detection in surveillance videos?")

May I know the difference between the two results?
And, Is there any difference in the experimental environment?

Thank you :)

**Comment by marco-rudolph** [comment]
Hello,
first, the feature extractor has been changed in CS-Flow (EfficientNet-B5 instead of AlexNet).
Second, in CS-Flow the nearest neighbor was calculated based on the full-sized feature map, while in DifferNet averaged feature maps, i.e. vectors, were used.

Best regards
Marco
