### ISSUE TITLE
How to do the test model with an image?

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [marco-rudolph/differnet#6]
@marco-rudolph Thank you for your work.
I would like to take the model then testing with an image, and show the score. How can I do that?

**Comment by marco-rudolph** [comment]
The lines from [here](https://github.com/marco-rudolph/differnet/blob/a484c6aebf8c82c48380770dfc34397182775e4a/train.py#L65) describe the evaluation.
[This line](https://github.com/marco-rudolph/differnet/blob/a484c6aebf8c82c48380770dfc34397182775e4a/train.py#L75) allows you to compute z and [this line](https://github.com/marco-rudolph/differnet/blob/a484c6aebf8c82c48380770dfc34397182775e4a/train.py#L88) and the following can be used to compute the anomaly score.

**Comment by nguyenanhtuan1008** [comment]
Thank you! I will try it!
