### ISSUE TITLE
How to judge whether the prediction result is OK or ng

### ISSUE THREAD

**Issue by machine52vision** [marco-rudolph/differnet#7]
How to judge whether the prediction result is OK or ng，and where is the threshold set？

**Comment by marco-rudolph** [comment]
See [here](https://github.com/marco-rudolph/differnet/issues/3#issuecomment-695962459).

> I would say the choice of theta could vary for different datasets. One could have a validation set of non-anomalies to estimate which threshold should be chosen for a specific target false positive rate.
